/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#1c1b1b",
        "surface-container": "#eceef2",
        "primary-fixed-dim": "#e9c400",
        "on-error-container": "#93000a",
        "inverse-primary": "#e9c400",
        "tertiary-container": "#d2d9e9",
        "surface-bright": "#f7f9fd",
        "inverse-surface": "#2d3134",
        "tertiary-fixed-dim": "#c0c7d6",
        "surface-dim": "#d8dade",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#c9c6c5",
        "on-background": "#191c1f",
        "on-secondary-container": "#656464",
        "on-primary-fixed-variant": "#554600",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#151c27",
        "inverse-on-surface": "#eff1f5",
        "surface-container-highest": "#e0e2e6",
        "primary-fixed": "#ffe171",
        "on-primary-fixed": "#221b00",
        "on-surface-variant": "#4d4632",
        "surface": "#ffffff",
        "surface-container-high": "#e6e8ec",
        "surface-tint": "#705d00",
        "on-error": "#ffffff",
        "primary": "#705d00",
        "on-surface": "#191c1f",
        "on-tertiary-container": "#585f6c",
        "tertiary": "#585f6c",
        "on-tertiary-fixed-variant": "#404754",
        "on-primary-container": "#705d00",
        "secondary-container": "#e5e2e1",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#e5e2e1",
        "surface-variant": "#e0e2e6",
        "tertiary-fixed": "#dce2f3",
        "primary-container": "#ffd60a",
        "background": "#ffffff",
        "surface-container-low": "#f2f4f8",
        "error": "#ba1a1a",
        "outline": "#7f775f",
        "outline-variant": "#d0c6ab",
        "on-secondary-fixed-variant": "#474646",
        "secondary": "#5f5e5e",
        "on-primary": "#ffffff"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-2xl": "4rem",
        "margin-mobile": "1.25rem",
        "space-sm": "0.5rem",
        "margin": "3rem",
        "gutter": "1.5rem",
        "gutter-sm": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "space-md": "1rem"
      },
      fontFamily: {
        "headline-lg": ["Oswald", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "display-mobile": ["Oswald", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-md-mobile": ["Oswald", "sans-serif"],
        "headline-sm": ["Oswald", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "label-caps": ["Oswald", "sans-serif"],
        "display": ["Oswald", "sans-serif"],
        "title-lg": ["Oswald", "sans-serif"],
        "label-technical": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Oswald", "sans-serif"],
        "headline-lg-mobile": ["Oswald", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["56px", { lineHeight: "64px", letterSpacing: "0.03em", fontWeight: "700" }],
        "body-sm": ["13px", { lineHeight: "18px", letterSpacing: "0", fontWeight: "400" }],
        "display-mobile": ["44px", { lineHeight: "48px", letterSpacing: "0.03em", fontWeight: "700" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-md-mobile": ["28px", { lineHeight: "32px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-sm": ["24px", { lineHeight: "30px", letterSpacing: "0.02em", fontWeight: "600" }],
        "title-md": ["16px", { lineHeight: "24px", letterSpacing: "0", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.12em", fontWeight: "600" }],
        "display": ["84px", { lineHeight: "92px", letterSpacing: "0.04em", fontWeight: "700" }],
        "title-lg": ["20px", { lineHeight: "26px", letterSpacing: "0.03em", fontWeight: "600" }],
        "label-technical": ["11px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["15px", { lineHeight: "24px", letterSpacing: "0", fontWeight: "400" }],
        "headline-md": ["36px", { lineHeight: "44px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["36px", { lineHeight: "40px", letterSpacing: "0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "400" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
