/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#1b1b1b",
        "on-surface-variant": "#4c4546",
        "surface-dim": "#dadada",
        "surface-bright": "#f9f9f9",
        "primary": "#000000",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#464747",
        "secondary-fixed": "#e3e2e2",
        "inverse-primary": "#c6c6c6",
        "on-tertiary-fixed": "#1b1b1b",
        "tertiary": "#000000",
        "surface": "#f9f9f9",
        "surface-variant": "#e2e2e2",
        "secondary": "#5e5e5e",
        "inverse-on-surface": "#f0f1f1",
        "on-secondary-fixed": "#1b1c1c",
        "surface-container": "#eeeeee",
        "on-background": "#1a1c1c",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#e2e2e2",
        "tertiary-container": "#1b1b1b",
        "on-error-container": "#93000a",
        "primary-container": "#1b1b1b",
        "surface-tint": "#5e5e5e",
        "surface-container-highest": "#e2e2e2",
        "on-tertiary-container": "#848484",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#c7c6c6",
        "on-secondary-container": "#646464",
        "on-surface": "#1a1c1c",
        "secondary-container": "#e3e2e2",
        "outline": "#7e7576",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "outline-variant": "#cfc4c5",
        "surface-container-high": "#e8e8e8",
        "inverse-surface": "#2f3131",
        "on-tertiary-fixed-variant": "#474747",
        "primary-fixed": "#e2e2e2",
        "tertiary-fixed-dim": "#c6c6c6",
        "primary-fixed-dim": "#c6c6c6",
        "surface-container-low": "#f3f3f4",
        "on-error": "#ffffff",
        "background": "#f9f9f9",
        "on-primary-container": "#848484",
        "on-primary-fixed-variant": "#474747"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "hairline": "1px",
        "gutter-desktop": "1.5rem",
        "sm": "0.75rem",
        "lg": "1.5rem",
        "margin-desktop": "2.5rem",
        "2xl": "3rem",
        "gutter-mobile": "1rem",
        "xl": "2rem",
        "xs": "0.5rem",
        "4xl": "6rem",
        "margin-mobile": "1.25rem",
        "2xs": "0.25rem",
        "3xl": "4rem",
        "md": "1rem"
      },
      "fontFamily": {
        "headline-lg": ["Inter", "sans-serif"],
        "mono-label": ["JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "display-hero": ["Inter", "sans-serif"],
        "display-hero-mobile": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "mono-spec": ["JetBrains Mono", "monospace"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      "fontSize": {
        "headline-lg": ["48px", { "lineHeight": "52px", "letterSpacing": "-0.03em", "fontWeight": "600" }],
        "mono-label": ["10px", { "lineHeight": "12px", "letterSpacing": "0.06em", "fontWeight": "400" }],
        "headline-lg-mobile": ["32px", { "lineHeight": "36px", "letterSpacing": "-0.025em", "fontWeight": "600" }],
        "display-hero": ["84px", { "lineHeight": "84px", "letterSpacing": "-0.04em", "fontWeight": "700" }],
        "display-hero-mobile": ["44px", { "lineHeight": "44px", "letterSpacing": "-0.03em", "fontWeight": "700" }],
        "body-sm": ["12px", { "lineHeight": "18px", "letterSpacing": "0em", "fontWeight": "400" }],
        "headline-md": ["28px", { "lineHeight": "34px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "24px", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "mono-spec": ["11px", { "lineHeight": "14px", "letterSpacing": "0.04em", "fontWeight": "500" }],
        "headline-sm": ["20px", { "lineHeight": "26px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "body-md": ["14px", { "lineHeight": "20px", "letterSpacing": "-0.005em", "fontWeight": "400" }]
      }
    }
  },
  plugins: [],
}
