<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Template;

class TemplateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $defaultTemplateDesc = 'Lisensi Desain UI/UX Eksklusif & Source Code Clean';
        $defaultServerDesc   = 'Cloud Server Hosting 1 Tahun, NVMe High Speed & Free SSL';
        $defaultServiceDesc  = 'Setup Domain, Deployment Instan & Garansi Pemeliharaan';

        $templates = [
            [
                'id' => 1,
                'name' => 'Rentcar - Sewa Mobil #1',
                'category' => 'Otomotif',
                'price' => 2000000,
                'template_price' => 1000000,
                'server_price' => 500000,
                'service_price' => 500000,
                'template_desc' => $defaultTemplateDesc,
                'server_desc' => $defaultServerDesc,
                'service_desc' => $defaultServiceDesc,
                'preview' => 'images/design_thumbnail/rentcar.webp',
                'demo_url' => '/demo/automotive',
                'description' => 'Showcase kendaraan dan penyewaan kendaraan untuk usaha Penyewaan Kendaraan',
                'tags' => 'Automotive, Rental Mobil, Responsive',
                'views' => 142,
                'is_active' => true,
            ],
            [
                'id' => 2,
                'name' => 'Deny Restaurant - Kalcer Restaurant',
                'category' => 'UMKM',
                'price' => 2000000,
                'template_price' => 1000000,
                'server_price' => 500000,
                'service_price' => 500000,
                'template_desc' => $defaultTemplateDesc,
                'server_desc' => $defaultServerDesc,
                'service_desc' => $defaultServiceDesc,
                'preview' => 'images/design_thumbnail/deny_restaurant.webp',
                'demo_url' => '/demo/restaurant-cafe-2',
                'description' => 'Cafe atau restaurant anak muda dengan gaya animasi kalcer, cocok untuk portofolio usaha.',
                'tags' => 'Restaurant, Cafe, Kalcer',
                'views' => 98,
                'is_active' => true,
            ],
            [
                'id' => 3,
                'name' => "Chef's Table - European Signature",
                'category' => 'UMKM',
                'price' => 2000000,
                'template_price' => 1000000,
                'server_price' => 500000,
                'service_price' => 500000,
                'template_desc' => $defaultTemplateDesc,
                'server_desc' => $defaultServerDesc,
                'service_desc' => $defaultServiceDesc,
                'preview' => 'images/design_thumbnail/chefs_table.webp',
                'demo_url' => '/demo/restaurant-cafe',
                'description' => 'Restaurant otentik, mewah dan berprestisius, dengan target korporat dan kelas internasional.',
                'tags' => 'Restaurant, Diner, Modern Theme',
                'views' => 115,
                'is_active' => true,
            ],
            [
                'id' => 4,
                'name' => 'IRONFORCE - Best Gym on Jakarta',
                'category' => 'Kecantikan',
                'price' => 2000000,
                'template_price' => 1000000,
                'server_price' => 500000,
                'service_price' => 500000,
                'template_desc' => $defaultTemplateDesc,
                'server_desc' => $defaultServerDesc,
                'service_desc' => $defaultServiceDesc,
                'preview' => 'images/design_thumbnail/ironforce.webp',
                'demo_url' => '/demo/beauty-wellness',
                'description' => 'Tempat kebugaran dan latihan anak gen z, tersebar sekitar jabodetabek, dengan fasilitas lengkap dan pelatih professional.',
                'tags' => 'Fitness, Gym, Personal Trainer',
                'views' => 230,
                'is_active' => true,
            ],
            [
                'id' => 5,
                'name' => 'Yayasan Bakti Nusantara',
                'category' => 'Komunitas',
                'price' => 2000000,
                'template_price' => 1000000,
                'server_price' => 500000,
                'service_price' => 500000,
                'template_desc' => $defaultTemplateDesc,
                'server_desc' => $defaultServerDesc,
                'service_desc' => $defaultServiceDesc,
                'preview' => 'images/design_thumbnail/batik_nusantara.webp',
                'demo_url' => '/demo/community-pro',
                'description' => 'Organisasi nirlaba sosial kemasyarakatan independen yang mendedikasikan diri untuk pengentasan kemiskinan, pemberdayaan ekonomi warga, dan kemanusiaan di Indonesia.',
                'tags' => 'Community, Yayasan, Donation',
                'views' => 74,
                'is_active' => true,
            ],
            [
                'id' => 6,
                'name' => 'Harapan kita',
                'category' => 'Komunitas',
                'price' => 2000000,
                'template_price' => 1000000,
                'server_price' => 500000,
                'service_price' => 500000,
                'template_desc' => $defaultTemplateDesc,
                'server_desc' => $defaultServerDesc,
                'service_desc' => $defaultServiceDesc,
                'preview' => 'images/design_thumbnail/harapan_kita.webp',
                'demo_url' => '/demo/organization',
                'description' => 'Organisasi non-profit mandiri dengan visi pengembangan pendidikan pada anak-anak di wilayah 3T (Tertinggal, Terdepan, dan Terluar).',
                'tags' => 'Community, Organization, Information Portal',
                'views' => 88,
                'is_active' => true,
            ],
            [
                'id' => 7,
                'name' => 'Konterku',
                'category' => 'UMKM',
                'price' => 2000000,
                'template_price' => 1000000,
                'server_price' => 500000,
                'service_price' => 500000,
                'template_desc' => $defaultTemplateDesc,
                'server_desc' => $defaultServerDesc,
                'service_desc' => $defaultServiceDesc,
                'preview' => 'images/design_thumbnail/konterku.webp',
                'demo_url' => '/demo/e-commerce',
                'description' => 'Branding dan digitalisasi usaha penjualan Handphone',
                'tags' => 'UMKM, Smartphone, Penjualan',
                'views' => 165,
                'is_active' => true,
            ],
            [
                'id' => 8,
                'name' => 'Denn House',
                'category' => 'Konstruksi & Properti',
                'price' => 2000000,
                'template_price' => 1000000,
                'server_price' => 500000,
                'service_price' => 500000,
                'template_desc' => $defaultTemplateDesc,
                'server_desc' => $defaultServerDesc,
                'service_desc' => $defaultServiceDesc,
                'preview' => 'images/design_thumbnail/denn_house.webp',
                'demo_url' => '/demo/property',
                'description' => 'Agen Penjualan atau Penyewaan Properti Harian, Bulanan dan Tahunan.',
                'tags' => 'Properti, Rumah, Showcase',
                'views' => 92,
                'is_active' => true,
            ],
            [
                'id' => 9,
                'name' => 'Chulla',
                'category' => 'Kecantikan',
                'price' => 2000000,
                'template_price' => 1000000,
                'server_price' => 500000,
                'service_price' => 500000,
                'template_desc' => $defaultTemplateDesc,
                'server_desc' => $defaultServerDesc,
                'service_desc' => $defaultServiceDesc,
                'preview' => 'images/design_thumbnail/chulla.webp',
                'demo_url' => '/demo/beauty-wellness-2',
                'description' => 'Branding skincare professional dengan tampilan website standar brand skincare lokal dan internasional',
                'tags' => 'Skincare, Kecantikan, Kosmetik',
                'views' => 210,
                'is_active' => true,
            ],
            [
                'id' => 10,
                'name' => 'SmartBelajar',
                'category' => 'Pendidikan',
                'price' => 2000000,
                'template_price' => 1000000,
                'server_price' => 500000,
                'service_price' => 500000,
                'template_desc' => $defaultTemplateDesc,
                'server_desc' => $defaultServerDesc,
                'service_desc' => $defaultServiceDesc,
                'preview' => 'images/design_thumbnail/smart_belajar.webp',
                'demo_url' => '/demo/smartbelajar',
                'description' => 'SmartBelajar membantu anak mengembangkan kemampuan belajar mandiri dalam Matematika dan Membaca sejak usia dini',
                'tags' => 'Les, Sekolah, Kursus',
                'views' => 134,
                'is_active' => true,
            ],
            [
                'id' => 11,
                'name' => 'Nivora Academy - Akademi digital, kursus, bootcamp',
                'category' => 'Pendidikan',
                'price' => 2000000,
                'template_price' => 1000000,
                'server_price' => 500000,
                'service_price' => 500000,
                'template_desc' => $defaultTemplateDesc,
                'server_desc' => $defaultServerDesc,
                'service_desc' => $defaultServiceDesc,
                'preview' => 'images/design_thumbnail/nivora_academy.webp',
                'demo_url' => '/demo/nivoraacademy',
                'description' => 'Akademi keterampilan digital Indonesia — kursus praktis, bootcamp intensif, dan mentor praktisi industri nyata.',
                'tags' => 'Akademi, Kursus, Profesi',
                'views' => 178,
                'is_active' => true,
            ],
            [
                'id' => 12,
                'name' => 'Aliansi Kepemimpinan Indonesia',
                'category' => 'Komunitas',
                'price' => 2000000,
                'template_price' => 1000000,
                'server_price' => 500000,
                'service_price' => 500000,
                'template_desc' => $defaultTemplateDesc,
                'server_desc' => $defaultServerDesc,
                'service_desc' => $defaultServiceDesc,
                'preview' => 'images/design_thumbnail/aliansi_kepemimpinan.webp',
                'demo_url' => '/demo/aliansi-kepemimpinan-indonesia',
                'description' => 'Wadah kolaborasi kepemimpinan, transformasi sosial, dan inovasi strategis generasi muda.',
                'tags' => 'Organisasi, Company Profile, Komunitas',
                'views' => 84,
                'is_active' => true,
            ],
            [
                'id' => 13,
                'name' => 'Teh.In - Teh Asli Nusantara',
                'category' => 'UMKM',
                'price' => 2000000,
                'template_price' => 1000000,
                'server_price' => 500000,
                'service_price' => 500000,
                'template_desc' => $defaultTemplateDesc,
                'server_desc' => $defaultServerDesc,
                'service_desc' => $defaultServiceDesc,
                'preview' => 'images/design_thumbnail/tehin.webp',
                'demo_url' => '/demo/tehin',
                'description' => 'Kesegaran teh asli nusantara, Diseduh segar setiap 4 jam dari pucuk daun teh hitam pegunungan tropis nusantara.',
                'tags' => 'UMKM, Teh, FnB',
                'views' => 122,
                'is_active' => true,
            ],
            [
                'id' => 14,
                'name' => 'Agak Rapi',
                'category' => 'Kecantikan',
                'price' => 2000000,
                'template_price' => 1000000,
                'server_price' => 500000,
                'service_price' => 500000,
                'template_desc' => $defaultTemplateDesc,
                'server_desc' => $defaultServerDesc,
                'service_desc' => $defaultServiceDesc,
                'preview' => 'images/design_thumbnail/agak_rapi.webp',
                'demo_url' => '/demo/agak-rapi',
                'description' => 'Barbershop ekslusif Jakarta; Pangkas presisi untuk yang mau agak rapi.',
                'tags' => 'Barbershop, Skena, Eksperimental',
                'views' => 156,
                'is_active' => true,
            ],
            [
                'id' => 15,
                'name' => 'Pinjam Mobil',
                'category' => 'Otomotif',
                'price' => 2000000,
                'template_price' => 1000000,
                'server_price' => 500000,
                'service_price' => 500000,
                'template_desc' => $defaultTemplateDesc,
                'server_desc' => $defaultServerDesc,
                'service_desc' => $defaultServiceDesc,
                'preview' => 'images/design_thumbnail/pinjammobil.webp',
                'demo_url' => '/demo/pinjammobil',
                'description' => 'Pinjam Mobil adalah tempat sewa mobil terbaik untuk anda yang ingin jalan-jalan, atau sekedar flexing ke cewe yang anda dekati.',
                'tags' => 'Otomotif, Penyewaan, Mobil',
                'views' => 105,
                'is_active' => true,
            ],
            [
                'id' => 16,
                'name' => 'FORCEVAULT - NIKE Authorize Seller at Indonesia',
                'category' => 'UMKM',
                'price' => 2000000,
                'template_price' => 1000000,
                'server_price' => 500000,
                'service_price' => 500000,
                'template_desc' => $defaultTemplateDesc,
                'server_desc' => $defaultServerDesc,
                'service_desc' => $defaultServiceDesc,
                'preview' => 'images/design_thumbnail/forcevault.webp',
                'demo_url' => '/demo/forcevault',
                'description' => 'Sepatu Nike Air Force 1 Premium Berkualitas',
                'tags' => 'Toko, Thrifting, Sepatu',
                'views' => 193,
                'is_active' => true,
            ],
            [
                'id' => 17,
                'name' => 'Elevasi',
                'category' => 'Konstruksi & Properti',
                'price' => 2000000,
                'template_price' => 1000000,
                'server_price' => 500000,
                'service_price' => 500000,
                'template_desc' => $defaultTemplateDesc,
                'server_desc' => $defaultServerDesc,
                'service_desc' => $defaultServiceDesc,
                'preview' => 'images/design_thumbnail/elevasi.webp',
                'demo_url' => '/demo/elevasi',
                'description' => 'Solusi kontraktor dan konstruksi bangunan terpercaya dengan kualitas terbaik dan bergaransi.',
                'tags' => 'Jasa, Konstruksi, Perusahaan',
                'views' => 87,
                'is_active' => true,
            ],
        ];

        foreach ($templates as $template) {
            Template::updateOrCreate(
                ['id' => $template['id']],
                $template
            );
        }
    }
}
